local sunglassesconfig = require "sunglasses"
sunglassesconfig.setup {
  filter_type = "SHADE",
  filter_percent = 0.65,
  excluded_filetypes = {
    "dashboard",
    "lspsagafinder",
    "packer",
    "checkhealth",
    "mason",
    "NvimTree",
    "neo-tree",
    "plugin",
    "lazy",
    "TelescopePrompt",
    "alpha",
    "sagafinder",
    "fugitiveblame",
    "starter",
    "NeogitPopup",
    "NeogitStatus",
    "DiffviewFiles",
    "DiffviewFileHistory",
    "DressingInput",
    "spectre_panel",
    "registers",
    "startuptime",
    "OverseerList",
    "Outline",
    "Navbuddy",
    "noice",
    "notify",
    "saga_codeaction",
    "sagarename",
  },
}
